name: Advanced Tracker Assistant

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Verify Deno installation
        run: deno --version 
      - name: Run Deno
        run: deno run --allow-net=api.notion.com --allow-env https://deno.land/x/automonth@v.1.0/src/main.ts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_PAGE: ${{ secrets.DATABASE_PAGE }}
      - name: Check workflow runs
        id: check_workflow
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file_name: '.github/workflows/main.yml',
              status: 'in_progress'
            });
            console.log(response.data);
            return response.data.total_count === 0;

      - name: Trigger new workflow
        if: steps.check_workflow.outputs.result == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: start_workflow
