name: Advanced Tracker Assistant

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: Verify Deno installation
        run: deno --version 
      - name: Run Deno
        run: deno run --allow-net --allow-env --allow-read https://raw.githubusercontent.com/nickerionalt/notioneo-aft-assistant/main/src/main.ts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION }}
          DATABASE_PAGE: ${{ secrets.DATABASE }}
