name: Restart

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Advanced Tracker Assistant"]
    types:
      - completed
      - failure

jobs:
  restart:
    name: Restart
    runs-on: ubuntu-latest
    steps:
      - name: Restart
        run: echo "Restarting"
