name: Restart

on:
  workflow_run:
    workflows: ["Advanced Tracker Assistant"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: Verify Deno installation
        run: deno --version 
      - name: Run Deno
        uses: nick-fields/retry@v2
        with:
          retry_on: error
          timeout_seconds: 5
          command: deno run --allow-net=api.notion.com --allow-env https://deno.land/x/automonth@v.1.0/src/main.ts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_PAGE: ${{ secrets.DATABASE_PAGE }}
